### ISSUE TITLE
*.twee should be considered a valid file extension

### ISSUE THREAD

**Issue by DanKaplanSES** [DustinWoods/vscode-twee2-syntax#2]
I would like to request that files with a twee extension get syntax highlighting. This is the file extension that tweego looks for. Thanks.

**Comment by MxAshUp** [comment]
@tieTYT what version of the extension are you using that's not getting the syntax highlighting?

**Comment by DanKaplanSES** [comment]
0.1.0

**Comment by MxAshUp** [comment]
Found the issue! Go ahead and update to 0.1.1 and you should see it resolved.
