### ISSUE TITLE
Collapsible passages

### ISSUE THREAD

**Issue by NQNStudios** [DustinWoods/vscode-twee2-syntax#7]
Thanks for making this!

One thing that would be nice is if I could collapse/expand each passage in a file.

**Comment by MxAshUp** [comment]
Hmmm I always assumed vscode did collapse/expand based on indentation. If you indent a passage, for example, you can collapse it.
![Peek 2020-08-06 19-44](https://user-images.githubusercontent.com/5541776/89603163-56322700-d81d-11ea-806b-e6588e47ae77.gif)

But I suspect I'm missing something more to this. Do you have an example using another language of expanding/collapsing that ignores indentations?

**Comment by MxAshUp** [comment]
Ah I'm onto it! https://code.visualstudio.com/api/language-extensions/language-configuration-guide#folding

**Comment by NQNStudios** [comment]
I didn't realize indentation was such a convenient way to fold anything in VSCode! Good to know.

But yeah, what I was thinking was that they shouldn't be required, `::[title]` would automatically be collapsible. But I wonder if the configuration you linked would throw a fit if the start of the next region has to be the end of the first region.

i.e.

```
{
  "folding": {
    "markers": {
      "start": "^::.*$",
      "end":   "^::.*$"      <-- Would this match then be ignored as the start of another region?
    }
  }
}
```

**Comment by MxAshUp** [comment]
I was just giving something like that a try, but you're right, I'm not sure how to tell it that the start of the next region is the end of the current one.

The closest I've got to something working is:
```json
{
    "markers": {
      "start": "^::.*$",
      "end":   ""
    }
```

This will only fold the first line in the passage.
I'm reading through the docs to see what we could work with.

Also interesting, I couldn't get `\n` to match. I tried setting `end` to `\n\n` or `^\n` but it seems it's matching on a line-by-line basis.

**Comment by NQNStudios** [comment]
Maybe this hacky way would work: 

```
"start": ":?:.*$",
"end": "^:"
```

~~Problem is it would probably start picking up colons that appear in embedded scripts.~~
Fixed (?) that by changing a . to a :

**Comment by MxAshUp** [comment]
Ah I see where you're going with that. Didn't seem to work though. (btw if you clone this repo, open with VS code and go to `run->start debugging` you can give these a try)

I think what VSCode is doing is labeling each line as either a start marker or end marker. And if a line is both, it ignores it(?)

**Comment by NQNStudios** [comment]
Another potential solution to this would be to make passage labels trigger
an automatic indent on the following lines. Not everyone would want this,
so it could be a togglable setting for the extension.

**Comment by MxAshUp** [comment]
Clever idea! Yeah definitely something that would be optional.

Another approach would be to implement a language server. This allows an extension to analyze an entire document, and return various interpretations about it, folding regions being one of them. Might be worth the effort.

**Comment by NQNStudios** [comment]
The tab thing is not a perfect workaround. I just found out that `[coffee
script]` blocks will cause a compilation error if the whole block is
indented.

**Comment by MxAshUp** [comment]
Ah good catch!

**Comment by MxAshUp** [comment]
Someone just started another twee extension, and they've made a ton more progress than I have here. They still don't have collapsible passages, but it may be easier to implement with what they have started. I opened this same issue over there: https://github.com/cyrusfirheir/twee3-language-tools/issues/2
